import rpa as r
r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win]')
r.keyboard('task Scheduler[enter]')
r.wait(2.5)
r.click('1.png')
r.wait(2.5)
r.click('name1.png')
r.wait(10)
r.hover('2.png')
r.click('2.png')
r.wait(2.5)
r.click('3.png')
r.snap('page.png', 'results.png')
r.close()